baseurl = "https://forestry.io"
copyright = ""
defaultContentLanguage = "en"
destination = "../dist/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
relativeURLs = false
title = "Forestry.io"
[markup]
defaultMarkdownHandler = "blackfriday"
[markup.blackFriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true
[markup.highlight]
codeFences = true
guessSyntax = true
style = "monokailight"
font-size = "0.85rem"
font-family = "monokai"
[[menu.docs]]
name = "Get started"
weight = 1
[[menu.docs]]
name = "Basic concepts"
weight = 2
[[menu.docs]]
name = "Nextflow scripting"
weight = 3
[[menu.docs]]
name = "Processes"
weight = 4
[[menu.docs]]
name = "Channels"
weight = 5
[[menu.docs]]
name = "Operators"
weight = 6
[[menu.docs]]
name = "Executors"
weight = 7
[[menu.docs]]
name = "Configuration"
weight = 8
[[menu.docs]]
name = "DSL2"
weight = 9
[[menu.docs]]
name = "Command line interface CLI"
weight = 10
[[menu.docs]]
name = "Amazon cloud"
weight = 11
[[menu.docs]]
name = "Amazon S3 storage"
weight = 12
[[menu.docs]]
name = "Google cloud"
weight = 13
[[menu.docs]]
name = "Conda environments"
weight = 14
[[menu.docs]]
name = "Docker containers"
weight = 15
[[menu.docs]]
name = "Docker containers"
weight = 16
[[menu.docs]]
name = "Shifter containers"
weight = 17
[[menu.docs]]
name = "Singularity containers"
weight = 18
[[menu.docs]]
name = "Podman containers"
weight = 19
[[menu.docs]]
name = "Apache Ignite"
weight = 20
[[menu.docs]]
name = "Kubernetes"
weight = 21
[[menu.docs]]
name = "Tracing and visulation"
weight = 22
[[menu.docs]]
name = "Pipeline sharing"
weight = 23
[[menu.docs]]
name = "Workflow introspection"
weight = 24
[[menu.docs]]
name = "Mail and notifications"
weight = 25
[[menu.docs]]
name = "Examples"
weight = 26









[[menu.footer]]
name = "Roadmap"
parent = "Product"
url = "https://portal.productboard.com/forestry/"
weight = 6
[[menu.footer]]
name = "Status"
parent = "Product"
url = "https://status.forestry.io"
weight = 7
[[menu.footer]]
name = "Company"
weight = 2
[[menu.footer]]
name = "Product"
weight = 1

[[menu.main]]
identifier = "useraccount"
name = "My Account"
url = "https://app.forestry.io/settings"
weight = 5
[[menu.main]]
identifier = "signup"
name = "Sign up"
url = "https://app.forestry.io/signup"
weight = 8
[[menu.main]]
identifier = "userdashboard"
name = "Dashboard"
url = "https://app.forestry.io/dashboard"
weight = 7
[[menu.main]]
identifier = "login"
name = "Login"
url = "https://app.forestry.io/login"
weight = 6
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true
[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]
[params]
dateformat = "January 2, 2006"
description = "Content management system for sites built with static site generators. Get the speed, security, and reliability of static and the power of a Headless CMS."
ghrepo = "https://github.com/forestryio/forestry.io"
ghrepo_edit = "https://github.com/forestryio/forestry.io/edit/master/hugo/content/"
ghrepo_new = "https://github.com/forestryio/forestry.io/issues/new"
gtmid = "GTM-KL5HP9Q"
images = ["/uploads/2018/01/OGimage-01-3x.jpg"]
mixpanelid = "8aaf5d792dd5bf875adae0b2adac8900"
[params.algolia]
params = ["tags", "categories", "authors"]
vars = ["date", "description", "dir", "path", "expirydate", "fuzzywordcount", "keywords", "kind", "lang", "lastmod", "permalink", "publishdate", "readingtime", "relpermalink", "summary", "title", "type", "url", "weight", "wordcount", "section"]
[params.cloudinary]
cloud_name = "forestry-io"
use_upload = false
baseurl = "https://res.cloudinary.com/forestry-io/image/fetch"
[params.cloudinary.lazysizes]
enabled = true
[params.cloudinary.presets.content]
max_width = 1920
min_width = 320
quality = 80
sizes = "auto"
steps = 10
width = 640
[params.cloudinary.presets.default]
quality = 80
[params.cloudinary.presets.feature]
max_width = 1920
min_width = 320
quality = 80
sizes = "(max-width: 76px) 100%, 800px"
steps = 10
width = 640
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[social]
email = "support@forestry.io"
slack = "https://join.slack.com/t/forestry-community/shared_invite/enQtNDAxMTU5NzcwMzA3LTY1MzM2YTZhN2Q2ZjkyMjk2ZmNhM2Y2ODIwYmU5YWRiNDYwMWRjNzhlOWJiMTg2NDc2ZWNlNjljOTNiNDZiZDk"
twitter = "forestryio"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
#the following lines enable hrefTargetBlank where all external links shall be generated with target='_blank'.
# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
