baseurl = ""
copyright = ""
defaultContentLanguage = "en"
destination = "../dist/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
relativeURLs = false
title = "Nextflow Tower Docs"
[markup]
defaultMarkdownHandler = "blackfriday"
[markup.blackFriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true
[markup.highlight]
codeFences = true
guessSyntax = true
style = "monokailight"
[[menu.docs]]
name = "Welcome"
weight = 1
[[menu.docs]]
name = "Getting Started"
weight = 2
[[menu.docs]]
name = "Compute Environments"
weight = 3
[[menu.docs]]
name = "Launching Pipelines"
weight = 4
[[menu.docs]]
name = "Monitoring Pipelines"
weight = 5
[[menu.docs]]
name = "Git Integration"
weight = 6
[[menu.docs]]
name = "Automation"
weight = 7
[[menu.docs]]
name = "API"
weight = 8
[[menu.faqs]]
name = "Glossary"
weight = 2


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true
[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]
[params]
dateformat = "January 2, 2006"
description = "Content management system for sites built with static site generators. Get the speed, security, and reliability of static and the power of a Headless CMS."
ghrepo = "https://github.com/seqeralabs/nf-tower"
ghrepo_edit = "https://github.com/seqeralabs/nf-tower-docs/edit/master/content/"
custom_css = ["css/custom/main.css"]

[params.algolia]
params = ["tags", "categories", "authors"]
vars = ["date", "description", "dir", "path", "expirydate", "fuzzywordcount", "keywords", "kind", "lang", "lastmod", "permalink", "publishdate", "readingtime", "relpermalink", "summary", "title", "type", "url", "weight", "wordcount", "section"]
[params.cloudinary]
cloud_name = "forestry-io"
use_upload = false
baseurl = "https://res.cloudinary.com/forestry-io/image/fetch"
[params.cloudinary.lazysizes]
enabled = true
[params.cloudinary.presets.content]
max_width = 1920
min_width = 320
quality = 80
sizes = "auto"
steps = 10
width = 640
[params.cloudinary.presets.default]
quality = 80
[params.cloudinary.presets.feature]
max_width = 1920
min_width = 320
quality = 80
sizes = "(max-width: 76px) 100%, 800px"
steps = 10
width = 640
[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Section"
weight = 200
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "date"
pattern = "2006"
weight = 10
[social]
email = "support@seqera.io"
twitter = "seqeralabs"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
#the following lines enable hrefTargetBlank where all external links shall be generated with target='_blank'.
# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
